### ISSUE TITLE
update numbers and order in the demo

### ISSUE THREAD

**Issue by aditya-chv** [nstreamio/stock-demo#43]
1. Would be good to move volume to the right side as it is not that important and have the decimals in x.abcd M (Millions) - instead of the current format with two decimals after zero. 
2. Add a percentage to each number under the movement column and limit to two decimals x.ab - currently, it is three decimals.
3. limit the stock price to two delimals x.ab - currently it is three decimals

These improvements will make the stock demo look a lot slicker.

**Comment by ajay-gov** [comment]
@cwjames19 can you fix these in the frontend? If it's too difficult we can do the number formatting in the backend for you.

**Comment by ajay-gov** [comment]
Currently the UI doesn't look good in light mode. Please fix this as well.
